---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Parameters: 
  ParaBucketName:
    Type: String 
    Description: S3 bucket Name.
Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref ParaBucketName
      BucketEncryption: 
        ServerSideEncryptionConfigration:
          - ServerSideEncryptionByDefault:
              SSEAlgorith: AES256 

  S3User:
    Type: AWS::IAM::User
    Properties:
      Policies: 
        - PolicyName: 
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*
  S3UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the Amazon S3 bucket.
  #S3BucketSecureURL:
 #   Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
  #  Description: Domain Name of the Amazon S3 bucket.  
      
  AccessKeyID:
    Value: !Ref S3UserAccessKey
  SecretAccessKey:
    Value: !GetAtt S3UserAccessKey.SecretAccessKey
  BucketName-1:
    Value: !Ref S3Bucket
  User:
    Value: !Ref S3User      