---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Code build Service  iam role cfn templates'

Resources: 
  CodeBuildRole: 
    Type: AWS::IAM::Role 
    Properties: 
      RoleName: 
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /service-role/
      Policies: 
        - PolicyName: "CodeBuildCICDAcessPolicy"
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "codecommit:GitPull"
                Resource:  
                  - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${ApplicationRepoName}
              - Effect: 
                Action:  
                  - "logs:CreationLogGroup"
                  - "Logs:CreateLogStream"
                  - "logs:PutLogEvents"   
                Resource:
                  - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Effect: Allow 
                Action: 
                  - "s3:Putobject"
                  - "s3:Getobject"
                  - "s3:getobjectVersion"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn::aws::s3:::codepipeline-${AWS::Region}-*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location} 
                  


