---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Ec2 instance profile role for access the s3 buckets'

Resources: 
  MyCICDEC2InstanceProfileRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 
              - 'sts:Assumerole'
      Path: /
      Policies: 
        - PolicyName: MyCICDEC2InstanceProfilePolicy 
          PolicyDocument: 
            Version: 2012-10-17 
            Statement:
              - Effect: Allow 
                Action: 
                  - 's3:Get*'
                  - 's3:List*'
                Resource: '*'  
